### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by piecioshka** [Kaosumaru/RPNParser#1]
Where they are?
How to run them?

:smile_cat:

**Comment by Kaosumaru** [comment]
WIP. Travis will be used in project, after I cleanup more important things (ie rename main project from ConsoleProject6 to something more appropriate)

**Comment by piecioshka** [comment]
Keep my finger crossed for that ;)

**Comment by Kaosumaru** [comment]
Project is now properly set up.
